Implement uniform return interface for js functions
authorizerdev/authorizer-js pull request #26
Opened 2023-10-30 10:34 UTC by shiftlabs1

#### What does this PR do?
@lakhansamani I don't want this PR merged . I just wanted to show a way we could integrate with this lib for JS using a consistent API by leveraging generic response interface. This means for every function call , we can easily check if the response is OK, extract and deal with the exception in a uniform manner . catching and throwing the exception within the library means every consumer needs to implement a catch block and alongside everything that can go wrong try to present users with some generic information while logging actual meaningful information from the library. This pattern above will ensure that i can dig into error[0] and display the message "joshua@shiftlabs.xyz has already signed up", instead of "An error occurred please try again".

If this is fine , i can modify the other functions to use ApiResponse<T> as well as the accompanying tests. I am using this currently on my project and invested. If you look at libs like supabase and nhost (i think) , they follow this pattern . I also do within my logic layer and leave the catch block at the entry level to deal with unhandled exceptions 

#### Which issue(s) does this PR fix?
Enhances Development and end user experience.

#### If this PR affects any API reference documentation, please share the updated endpoint references
API docs

2023-10-30 13:30 UTC, shiftlabs1 commented
Also message response like in magicLinkLogin does not tell if that call was a success or failure, given that its free text with no defined pattern. I think all functions will benefit from this and we can destructure like ``` const {ok,error,response} = await authRef.signUp({...signUpPayload}) ``` and handle based on the Ok flag to look for success message in the response?.message or the error payload in error?.message

2023-11-01 05:28 UTC, lakhansamani commented
@shiftlabs1 I like this approach, lets try to add this for all queries 👍

2023-11-01 14:46 UTC, shiftlabs1 commented
@lakhansamani  I have updated the lib also pulled in the latest change for ValidateSession function . Please review. I am guessing the docs will need updating to reflect this. The examples especially

2023-11-02 02:59 UTC, lakhansamani commented
Thanks @shiftlabs1 I will hold this release for a bit as all other SDKs needs to be updated.

2023-11-02 07:21 UTC, shiftlabs1 commented
Oh i see. The other framework SDKs depend on this . I can look at the one for Svelte

2023-11-23 17:12 UTC, siimsams commented
Hey!

I have fixed the lint issue. Sadly i can't edit your branch.

2023-11-23 17:30 UTC, shiftlabs1 commented
Ok. I will pull the latest and merge into mine in a bit

2023-11-24 08:00 UTC, siimsams commented
You can merge in my changes from here:
https://github.com/authorizerdev/authorizer-js/pull/29

2023-11-24 14:09 UTC, shiftlabs1 commented
@lakhansamani  changes merged in here and checks passed

2023-11-25 04:08 UTC, lakhansamani commented
@shiftlabs1 / @siimsams I was just thinking more about it, what if we follow standard graphql response pattern since this is more of graphql apis?

`const { error, data } = await login(...)`

2023-11-25 16:50 UTC, siimsams commented
Hmm, not sure what you mean by this exactly. You can destructure the response given here aswell. Or are you suggesting the removal ok boolean in [ApiResponse](https://github.com/authorizerdev/authorizer-js/pull/26/files#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410a?

2023-11-26 14:56 UTC, lakhansamani requested changes

2023-11-26 17:05 UTC, shiftlabs1 commented
> Hmm, not sure what you mean by this exactly. You can destructure the response given here aswell. Or are you suggesting the removal ok boolean in [ApiResponse](https://github.com/authorizerdev/authorizer-js/pull/26/files#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410a)?

Because ApiResponse<T> now has Ok . GenericResponse is now a type T with message as the only property . So you can return ApiResponse<GenericResponse> from a method call

2023-11-26 17:06 UTC, shiftlabs1 commented on .gitignore
> -lib
That was my bad , i removed it while testing the lib via github

2023-11-26 17:11 UTC, shiftlabs1 commented on .gitignore
> -lib
updated now

2023-11-26 17:24 UTC, siimsams commented on src/types.ts
> +  ok: boolean
I'm not sure we need it. We can keep this response as similar as possible to GraphQL spec. 

https://graphql.org/learn/serving-over-http/#response

2023-11-26 17:24 UTC, siimsams commented on src/types.ts
> +  response: T | undefined
Lets rename this to data.

2023-11-26 17:24 UTC, siimsams commented on src/types.ts
> +  error: Error | undefined
There might be multiple errors. 
<img width="585" alt="Screenshot 2023-11-26 at 19 24 38" src="https://github.com/authorizerdev/authorizer-js/assets/17649698/a1048f15-b457-4083-aa97-9ebf5b582893">

2023-11-26 17:27 UTC, lakhansamani commented on src/types.ts
> +  error: Error | undefined
Correct, lets return one error at a time, so if there multiple errors, user will any way see that in next call.

2023-11-26 17:48 UTC, siimsams commented on src/types.ts
> +  error: Error | undefined
Not sure if returning 1 error at a time is easier. They can pick the first error if it makes their life easier. But have the option of using all of the errors if they want to. The image is of the response from authorizer api. 

In this case it would just be 

`errors: Error[] | undefined`

2023-11-27 10:53 UTC, shiftlabs1 commented on src/types.ts
> +  error: Error | undefined
in the graphqlQuery call for example we are creating a new Error off of the first error entry from json.errors , so Deep down we are only passing out one error at a time, To change the property here to errors and return Error[], would mean returning returning json.errors ( How do you throw that )

```

    const json = await res.json()

    if (json.errors && json.errors.length) {
      console.error(json.errors)
      throw new Error(json.errors[0].message)
    }
```
. I am making other recommended changes like 1. changing response to data in ApiResponse<T>

2023-11-27 10:56 UTC, shiftlabs1 commented on src/types.ts
> +  ok: boolean
I agree we can take the ok out . on the calling service ok will simply be errors.lenth === 0 (that is if we keeping errors as Error[] , ) or ok will be !error . We just need to finalise on Error vs Error[] then we can take ok out

2023-11-27 15:47 UTC, lakhansamani commented
I still see it in changes

<img width="359" alt="Screenshot 2023-11-27 at 9 16 44 PM" src="https://github.com/authorizerdev/authorizer-js/assets/6964334/70e53e4f-ff29-4690-b9e6-c63dba88133f">

2023-11-27 16:16 UTC, siimsams approved these changes
Lib has been removed. Nice job! Thank you for your contribution!

2023-12-04 23:24 UTC, merged